=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2009 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature feature*>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, ruri+, header*, data?, verify*, grabheader*, grabproperty*, grabelement*)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, variable)>

	<!ELEMENT test-suite (require-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/implicitcompatibility.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2008 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test the Schedule-Tag behavior</description>

	<start>
		<request user="$userid1:" pswd="$pswd1:">
			<method>GET</method>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>GET</method>
			<ruri>$calendarpath2:/</ruri>
		</request>
		<request user="$userid3:" pswd="$pswd3:">
			<method>GET</method>
			<ruri>$calendarpath3:/</ruri>
		</request>
	</start>
	
	<test-suite name='Organizer Merge - insignificant change' ignore='no'>
		<test name='1'>
			<description>Organizer invites Attendee</description>
			<request print-response='no'>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Organizer checks data</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/implicit/compatibility/2.ics</value>
					</arg>
				</verify>
				<grabheader>
					<name>ETag</name>
					<variable>$etag-organizer:</variable>
				</grabheader>
			</request>
		</test>
		<test name='3'>
			<description>Attendee Inbox Item</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$pathprefix2:/$inbox:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/3.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>1</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Attendee has data</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$calendarpath2:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/implicit/compatibility/4.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>Attendee deletes Inbox Item</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$pathprefix2:/$inbox:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>DELETE</method>
				<ruri>$</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>204</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>Attendee -> Accepted</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$calendarpath2:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PUT</method>
				<ruri>$</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/5.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>Organizer Inbox Item</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$pathprefix1:/$inbox:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/3.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>1</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='8'>
			<description>Organizer data changed</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/implicit/compatibility/6.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='9'>
			<description>Organizer deletes Inbox Item</description>
			<request print-response='no'>
				<method>GETNEW</method>
				<ruri>$pathprefix1:/$inbox:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response='no'>
				<method>DELETE</method>
				<ruri>$</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>204</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='10'>
			<description>Organizer adds VALARM to one instance</description>
			<request print-response='no'>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<header>
					<name>If-Match</name>
					<value>$etag-organizer:</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/7.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='11'>
			<description>Organizer checks data</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/implicit/compatibility/8.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='12'>
			<description>Attendee no Inbox Item</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$pathprefix2:/$inbox:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/compatibility/3.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='13'>
			<description>Clean-up</description>
			<request user="$userid1:" pswd="$pswd1:">
				<method>DELETEALL</method>
				<ruri>$calendarpath1:/</ruri>
			</request>
			<request user="$userid1:" pswd="$pswd1:">
				<method>DELETEALL</method>
				<ruri>$pathprefix1:/$inbox:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:">
				<method>DELETEALL</method>
				<ruri>$calendarpath2:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:">
				<method>DELETEALL</method>
				<ruri>$pathprefix2:/$inbox:/</ruri>
			</request>
		</test>
	</test-suite>

	<end>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$calendarpath1:/</ruri>
			<ruri>$pathprefix1:/$inbox:/</ruri>
			<ruri>$calendarpath2:/</ruri>
			<ruri>$pathprefix2:/$inbox:/</ruri>
			<ruri>$calendarpath3:/</ruri>
			<ruri>$pathprefix3:/$inbox:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/sharing-invites.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2010 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test calendar sharing invitations</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>shared-calendars</feature>
	</require-feature>

	<start>
		<request user="$userid1:" pswd="$pswd1:">
			<method>DELETEALL</method>
			<ruri>$notificationpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$notificationpath2:/</ruri>
		</request>
		<request end-delete="yes">
			<method>MKCALENDAR</method>
			<ruri>$pathprefix1:/shared/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/Common/MKCALENDAR/sharedcalendar.xml</filepath>
			</data>
			<verify>
				<callback>statusCode</callback>
			</verify>
		</request>
	</start>
	
	<test-suite name='Send new invite'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/new/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>WAITCOUNT 1</method>
				<ruri>$notificationpath2:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$notificationpath2:/</ruri>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/sharing/invites/new/2.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}dtstamp</value>
						<value>{http://calendarserver.org/ns/}uid</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Notification type property</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/new/3.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{http://calendarserver.org/ns/}notificationtype/{http://calendarserver.org/ns/}invite-notification[@shared-type="calendar"]</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Update new invite'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/updatenew/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>WAITCOUNT 1</method>
				<ruri>$notificationpath2:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$notificationpath2:/</ruri>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/sharing/invites/updatenew/2.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}dtstamp</value>
						<value>{http://calendarserver.org/ns/}uid</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Notification type property</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/updatenew/3.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{http://calendarserver.org/ns/}notificationtype/{http://calendarserver.org/ns/}invite-notification[@shared-type="calendar"]</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Uninvite new invite'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/uninvitenew/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$notificationpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Attempt broken invite'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/broken/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>424</name>
						<value>$cuaddr2:</value>
					</arg>
					<arg>
						<name>403</name>
						<value>mailto:bogus@example.net</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$notificationpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Delete new invite'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/sharing/invites/new/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$notificationpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>1</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>DELETE collection</description>
			<request print-response='no'>
				<method>DELETE</method>
				<ruri>$pathprefix1:/shared/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$notificationpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$notificationpath1:/</ruri>
			<ruri>$notificationpath2:/</ruri>
			<ruri>$notificationpath3:/</ruri>
			<ruri>$notificationpath4:/</ruri>
		</request>
	</end>

</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/servertoserveroutgoing.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest ignore-all="yes">
	<description>Test POST method in CalDAV</description>

	<start/>
	
	<test-suite name="POST free-busy" ignore='no'>
		<test name='1'>
			<description>POST free busy one valid user</description>
			<request print-response='yes'>
				<method>POST</method>
				<header>
					<name>Originator</name>
					<value>$cuaddr1:</value>
				</header>
				<header>
					<name>Recipient</name>
					<value>mailto:remote01@example.org</value>
				</header>
				<ruri>$pathprefix:/$outbox:/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/servertoserver/8.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>2.0;Success</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name="POST invite" ignore='no'>
		<test name='1'>
			<description>POST invite one valid user</description>
			<request print-response='yes'>
				<method>POST</method>
				<header>
					<name>Originator</name>
					<value>$cuaddr1:</value>
				</header>
				<header>
					<name>Recipient</name>
					<value>mailto:remote01@example.org</value>
				</header>
				<ruri>$pathprefix:/$outbox:/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/servertoserver/9.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>2.0;Success</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/directory.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test GET on collections to ensure proper directory listing</description>

	<start/>
	
	<test-suite name='GET on collections'>
		<test name='1'>
			<description>GET on root collection</description>
			<request>
				<method>GET</method>
				<ruri>/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>GET on principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>GET on user principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/users/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>GET on group principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/groups/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>GET on locations principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/locations/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>GET on resources principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/resources/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>GET on __uids__ principals collection</description>
			<request>
				<method>GET</method>
				<ruri>/principals/__uids__/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='8'>
			<description>GET on calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='9'>
			<description>GET on user calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/users/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='10'>
			<description>GET on group calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/groups/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='11'>
			<description>GET on locations calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/locations/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='12'>
			<description>GET on resources calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/resources/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='13'>
			<description>GET on __uids__ calendars collection</description>
			<request>
				<method>GET</method>
				<ruri>/calendars/__uids__/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/availability.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<description>Test PUT method in CalDAV</description>

	<start/>
	
	<test-suite name='PUT VAVAILABILITY'>
		<test name='1' ignore='no'>
			<description>PUT availability</description>
			<request end-delete="yes">
				<method>PUT</method>
				<ruri>1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/availability/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>ETag$\"0dd19df90dcc91cf6c549ff7ca69ca3a\"</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>1.ics</ruri>
				<verify>
					<callback>dataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/availability/1.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>
