=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2009 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature feature*>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, ruri+, header*, data?, verify*, grabheader*, grabproperty*, grabelement*)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, variable)>

	<!ELEMENT test-suite (require-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/encodedURIs.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start>
		<request end-delete='yes'>
			<method>MKCOL</method>
			<ruri>$pathprefix:/collection%201/</ruri>
		</request>
		<request end-delete='yes'>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/calendar%202/</ruri>
		</request>
		<request end-delete='yes'>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/calendar%203/</ruri>
		</request>
	</start>

	<test-suite name='regular resource'>
		<test name='1'>
			<description>PUT</description>
			<request print-response='no' end-delete='yes'>
				<method>PUT</method>
				<ruri>$pathprefix:/collection%201/2%20a.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>!Location</value>
					</arg>
				</verify>
			</request>
		</test>

		<test name='2'>
			<description>COPY</description>
			<request print-response='no' end-delete='yes'>
				<method>COPY</method>
				<header>
					<name>Destination</name>
					<value>$host:$pathprefix:/collection%201/2_2%20a.ics</value>
				</header>
				<ruri>$pathprefix:/collection%201/2%20a.ics</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$host:$pathprefix:/collection%201/2_2%20a.ics</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/collection%201/2_2%20a.ics</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value/>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix:/collection%201/2_2%20a.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>MOVE</description>
			<request print-response='no' end-delete='yes'>
				<method>MOVE</method>
				<header>
					<name>Destination</name>
					<value>$host:$pathprefix:/collection%201/2_3%20a.ics</value>
				</header>
				<ruri>$pathprefix:/collection%201/2%20a.ics</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$host:$pathprefix:/collection%201/2_3%20a.ics</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/collection%201/2_2%20a.ics</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value/>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix:/collection%201/2_2%20a.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='calendar resource'>
		<test name='1'>
			<description>PUT</description>
			<request print-response='no' end-delete='yes'>
				<method>PUT</method>
				<ruri>2%20a.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>!Location</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>COPY</description>
			<request print-response='no' end-delete='yes'>
				<method>COPY</method>
				<header>
					<name>Destination</name>
					<value>$host:$pathprefix:/calendar%202/2_2%20a.ics</value>
				</header>
				<ruri>2%20a.ics</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$host:$pathprefix:/calendar%202/2_2%20a.ics</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/calendar%202/2_2%20a.ics</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value/>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix:/calendar%202/2_2%20a.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>MOVE</description>
			<request print-response='no' end-delete='yes'>
				<method>MOVE</method>
				<header>
					<name>Destination</name>
					<value>$host:$pathprefix:/calendar%203/2_3%20a.ics</value>
				</header>
				<ruri>2%20a.ics</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$host:$pathprefix:/calendar%203/2_3%20a.ics</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/calendar%203/2_3%20a.ics</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value/>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix:/calendar%203/2_3%20a.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>
