=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2009 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature feature*>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, ruri+, header*, data?, verify*, grabheader*, grabproperty*, grabelement*)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, variable)>

	<!ELEMENT test-suite (require-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/implicitauto9.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test implicit scheduling for auto-accept where proxy change is preserved</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>auto-accept</feature>
		<feature>implicit-scheduling</feature>
	</require-feature>

	<start/>
	
	<test-suite name='#1 Decline one valid instance'>
		<test name='1'>
			<description>Create new event</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto9/suite1/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>One item in user01 Inbox</description>
			<request>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='3'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>No items in resource01 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>PROPFIND</method>
				<ruri>$rinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GETNEW</method>
				<ruri>$rcalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/3.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>Proxy decline resource01 Calendar</description>
			<request>
				<method>PUT</method>
				<ruri>$</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto9/suite1/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>One item in user01 Inbox</description>
			<request>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='8'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/5.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='9'>
			<description>Update event summary - resource partstat unchanged</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto9/suite1/6.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>DELAY</method>
				<ruri>1</ruri>
			</request>
		</test>
		<test name='10'>
			<description>No items in user01 Inbox</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$inboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='11'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/7.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='12'>
			<description>No items in resource01 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>PROPFIND</method>
				<ruri>$rinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='13'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GETNEW</method>
				<ruri>$rcalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/8.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='14'>
			<description>Re-invite declined instance</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto9/suite1/9.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='15'>
			<description>One item in user01 Inbox</description>
			<request>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='16'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/10.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='17'>
			<description>No items in resource01 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>PROPFIND</method>
				<ruri>$rinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='18'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GETNEW</method>
				<ruri>$rcalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto9/suite1/11.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='-1'>
			<description>Clean-up inboxes</description>
			<request>
				<method>DELETEALL</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>DELETEALL</method>
				<ruri>$rinboxpath1:/</ruri>
			</request>
		</test>
	</test-suite>

	<end>
		<request>
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>WAITCOUNT 0</method>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CardDAV/mkcol.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2010 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='MKCOL with body'>
		<test name='1'>
			<description>MKCOL with correct request body</description>
			<request end-delete='yes'>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest1/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>201</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>MKCOL with correct request body on existing resource</description>
			<request>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest1/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/1.xml</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{DAV:}resource-must-be-null</value>
					</arg>
				</verify>
			</request>
		</test>
 		<test name='3'>
			<description>MKCOL with incorrect request body</description>
			<request end-delete='yes' print-response='no'>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest2/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}getetag</value>
						<value>{DAV:}displayname</value>
						<value>{urn:ietf:params:xml:ns:carddav}addressbook-description</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$addressbookhome1:/adbktest2/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>MKCOL with incorrect request body on existing resource</description>
			<request>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest1/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/2.xml</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{DAV:}resource-must-be-null</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>MKCOL with incorrect resourcetype on new resource</description>
			<request>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest3/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/3.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>400</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>

</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/CalDAV/implicitauto11.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test implicit scheduling for auto-accept location where hidden instances are used</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>auto-accept</feature>
		<feature>implicit-scheduling</feature>
	</require-feature>

	<start>
		<request user="$userid1:" pswd="$pswd1:">
			<method>GET</method>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>GET</method>
			<ruri>$calendarpath2:/</ruri>
		</request>
		<request>
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$inboxpath2:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rinboxpath1:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</start>
	
	<test-suite name='#1 Non-recurring'>
		<test name='1'>
			<description>Create recurring event - resource invited to two instances only</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto11/suite1/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>One item in user01 Inbox</description>
			<request>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='3'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto11/suite1/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>No items in resource01 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>PROPFIND</method>
				<ruri>$rinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GETNEW</method>
				<ruri>$rcalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto11/suite1/3.ics</value>
					</arg>
				</verify>
				<graburi>$r1:</graburi>
			</request>
		</test>
		<test name='6'>
			<description>Proxy removes first instance to decline it</description>
			<request>
				<method>PUT</method>
				<ruri>$r1:</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto11/suite1/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GET</method>
				<ruri>$r1:</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto11/suite1/4.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='8'>
			<description>One item in user01 Inbox</description>
			<request>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='9'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto11/suite1/5.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='10'>
			<description>Organizer cancels second instance</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/auto11/suite1/6.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='11'>
			<description>One item in user01 Calendar</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/auto11/suite1/7.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='12'>
			<description>No item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>WAITCOUNT 0</method>
				<ruri>$rcalendarpath1:/</ruri>
			</request>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>GET</method>
				<ruri>$r1:</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='-1'>
			<description>Clean-up inboxes</description>
			<request>
				<method>DELETEALL</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:">
				<method>WAITDELETEALL 3</method>
				<ruri>$inboxpath2:/</ruri>
			</request>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>DELETEALL</method>
				<ruri>$rinboxpath1:/</ruri>
			</request>
		</test>
	</test-suite>

	<end>
		<request>
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>WAITDELETEALL 1</method>
			<ruri>$inboxpath2:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$calendarpath2:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rinboxpath1:/</ruri>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scripts/tests/propfind.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start/>
	
	<test-suite name='regular prop finds'>
		<test name='1'>
			<description>PROPFIND of basic properties depth=0</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of basic properties depth=1</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of basic properties depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND getcontentlength=0</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/7.txt</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>DAV:getcontentlength$</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop names'>
		<test name='1'>
			<description>PROPFIND of property names depth=0</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of property names depth=1</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of property names depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop all'>
		<test name='1'>
			<description>PROPFIND of all properties depth=0</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/3.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of all properties depth=1</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/3.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of all properties depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/3.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop errors'>
		<test name='1'>
			<description>PROPFIND with invalid elements</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/4.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>4xx</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of unknown element</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/5.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>4xx</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND with one unknown property</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/propfinds/6.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>
