=== svn2github/calendarserver-raw/CalendarServer/branches/new-store/conf/auth/augments.dtd
<!--
Copyright (c) 2009-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!ELEMENT augments (record*) >

  <!ELEMENT record (uid, enable, hosted-at?, enable-calendar?, enable-addressbook?, auto-schedule?)>
    <!ATTLIST record repeat CDATA "1">

  <!ELEMENT uid                (#PCDATA)>
  <!ELEMENT enable             (#PCDATA)>
  <!ELEMENT hosted-at          (#PCDATA)>
  <!ELEMENT enable-calendar    (#PCDATA)>
  <!ELEMENT enable-addressbook (#PCDATA)>
  <!ELEMENT auto-schedule      (#PCDATA)>
>

=== svn2github/calendarserver-raw/CalendarServer/branches/release/CalendarServer-3.1-dev/calendarserver/tools/test/deprovision/augments.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>E9E78C86-4829-4520-A35D-70DDADAB2092</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record>
    <uid>291C2C29-B663-4342-8EA1-A055E6A04D65</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
</augments>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/glyph/sql-store/twistedcaldav/directory/test/augments-test-default.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <hosted-at>00001</hosted-at>
  </record>
  <record>
    <uid>AA*</uid>
    <enable>true</enable>
    <hosted-at>00001</hosted-at>
  </record>
  <record>
    <uid>AB*</uid>
    <enable>false</enable>
  </record>
  <record>
    <uid>B*</uid>
    <enable>true</enable>
    <hosted-at>00002</hosted-at>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record>
    <uid>C*</uid>
    <enable>true</enable>
    <hosted-at>00003</hosted-at>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</uid>
    <enable>true</enable>
  </record>
  <record>
    <uid>6423F94A-6B76-4A3A-815B-D52CFD77935D</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record>
    <uid>5A985493-EE2C-4665-94CF-4DFEA3A89500</uid>
    <enable>false</enable>
  </record>
  <record>
    <uid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</uid>
    <enable>true</enable>
    <enable-calendar>false</enable-calendar>
    <enable-addressbook>false</enable-addressbook>
  </record>
  <record>
    <uid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</uid>
    <enable>true</enable>
    <hosted-at>00001</hosted-at>
  </record>
  <record>
    <uid>543D28BA-F74F-4D5F-9243-B3E3A61171E5</uid>
    <enable>true</enable>
    <hosted-at>00002</hosted-at>
  </record>
  <record>
    <uid>6A73326A-F781-47E7-A9F8-AF47364D4152</uid>
    <enable>true</enable>
    <hosted-at>00002</hosted-at>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
</augments>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/sagen/usingqueue/conf/auth/augments-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2013 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE augments SYSTEM "augments.dtd">

<augments>
  <record>
    <uid>Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record repeat="10">
    <uid>location%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
  <record repeat="4">
    <uid>resource%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>resource05</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>none</auto-schedule-mode>
  </record>
  <record>
    <uid>resource06</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>accept-always</auto-schedule-mode>
  </record>
  <record>
    <uid>resource07</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>decline-always</auto-schedule-mode>
  </record>
  <record>
    <uid>resource08</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>accept-if-free</auto-schedule-mode>
  </record>
  <record>
    <uid>resource09</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>decline-if-busy</auto-schedule-mode>
  </record>
  <record>
    <uid>resource10</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>automatic</auto-schedule-mode>
  </record>
  <record>
    <uid>resource11</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
    <auto-schedule-mode>decline-always</auto-schedule-mode>
    <auto-accept-group>group01</auto-accept-group>
  </record>
  <record repeat="10">
    <uid>group%02d</uid>
    <enable>true</enable>
  </record>
  <record>
    <uid>disabledgroup</uid>
    <enable>false</enable>
  </record>
  <record>
    <uid>delegatedroom</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>false</enable-addressbook>
    <auto-schedule>false</auto-schedule>
  </record>
</augments>

=== svn2github/calendarserver-raw/CalendarServer/tags/release/CalendarServer-4.2/calendarserver/tools/test/calverify/augments.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2012 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record>
    <uid>75EA36BE-F71B-40F9-81F9-CF59BF40CA8F</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <auto-schedule>true</auto-schedule>
  </record>
</augments>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/wsanchez/deployment/conf/augments-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2009 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE augments SYSTEM "augments.dtd">

<augments>
  <record>
    <uid>admin</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record>
    <uid>apprentice</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record repeat="99">
    <uid>user%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record repeat="10">
    <uid>public%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record repeat="10">
    <uid>location%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <auto-schedule>true</auto-schedule>
  </record>
  <record repeat="10">
    <uid>resource%02d</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <auto-schedule>true</auto-schedule>
  </record>
  <record repeat="4">
    <uid>group%02d</uid>
    <enable>true</enable>
  </record>
  <record>
    <uid>disabledgroup</uid>
    <enable>false</enable>
  </record>
</augments>
