=== svn2github/calendarserver-raw/CalendarServer/trunk/conf/repository.dtd
<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

This file contains Original Code and/or Modifications of Original Code
as defined in and that are subject to the Apple Public Source License
Version 2.0 (the 'License'). You may not use this file except in
compliance with the License. Please obtain a copy of the License at
http://www.opensource.apple.com/apsl/ and read it before using this
file.

The Original Code and all software distributed under the License are
distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
Please see the License for the specific language governing rights and
limitations under the License.

DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<!ELEMENT repository (docroot, accounts) >

  <!ELEMENT docroot (collection) >
	<!ATTLIST docroot auto-principal-collection-set (yes|no) "yes">

    <!ELEMENT collection (pytype?, params, properties, members)>
      <!ATTLIST collection name CDATA ""
                             tag (none|principals|calendars) "none">
      <!ELEMENT pytype     (#PCDATA)>
      <!ELEMENT params     (param*)>
        <!ELEMENT param    (key, value)>
          <!ELEMENT key    (#PCDATA)>
          <!ELEMENT value  (#PCDATA)>          
      <!ELEMENT properties (acl?, prop*)>
        <!ELEMENT prop     ANY>
      <!ELEMENT members    (collection*)>

      <!ELEMENT acl                   (ace*) >  
           <!ELEMENT ace              (principal, (grant|deny), protected?, inheritable?)>
             <!ELEMENT principal      (href | all | authenticated | unauthenticated)>
            <!ELEMENT href            (#PCDATA)>
            <!ELEMENT all             EMPTY>
            <!ELEMENT authenticated   EMPTY>
            <!ELEMENT unauthenticated EMPTY>
          <!ELEMENT grant             (privilege+)>
          <!ELEMENT deny              (privilege+)>
            <!ELEMENT privilege       ANY>
          <!ELEMENT protected         EMPTY>
          <!ELEMENT inheritable       EMPTY>

          <!ELEMENT read EMPTY>

  <!ELEMENT accounts (user*) >

    <!ELEMENT user (uid, pswd, name, cuaddr*, calendar*, acl?, autorespond?)>
      <!ATTLIST user repeat CDATA "1">
      <!ELEMENT uid         (#PCDATA)>
      <!ELEMENT pswd        (#PCDATA)>
      <!ELEMENT name        (#PCDATA)>
      <!ELEMENT cuaddr      (#PCDATA)>
      <!ELEMENT calendar    (#PCDATA)>
      <!ELEMENT autorespond EMPTY>

=== svn2github/calendarserver-raw/CalendarServer/trunk/conf/repository.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE repository SYSTEM "repository.dtd">

<repository>

  <docroot auto-principal-collection-set="yes">
    <collection>
      <pytype>twistedcaldav.root.RootResource</pytype>
      <properties>
        <acl>
          <ace>
            <principal><all/></principal>
            <grant><privilege><read/></privilege></grant>
          </ace>
          <ace>
            <principal><href>/principals/user/admin</href></principal>
            <grant><privilege><all/></privilege></grant>
            <protected/>
            <inheritable/>
          </ace>
        </acl>
      </properties>
      <members>
        <collection name="principals">
          <pytype>twistedcaldav.directory.principal.DirectoryPrincipalProvisioningResource</pytype>
          <properties/>
          <members/>
        </collection>
        <collection name="calendars">
          <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
          <properties/>
          <members/>
        </collection>
      </members>
    </collection>
  </docroot>

  <authentication>
    <basic enable="yes" onlyssl="yes" credentials="directory" node="/Search">
      <realm></realm>
    </basic>
    <digest enable="no" onlyssl="no" credentials="property">
      <realm></realm>
    </digest>
    <kerberos enable="no" onlyssl="no">
      <service></service>
    </kerberos>
  </authentication>

</repository>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/cdaboo/dropbox/conf/repository.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE repository SYSTEM "repository.dtd">

<repository>

  <docroot auto-principal-collection-set="yes">
    <collection>
      <pytype>twisted.web2.dav.static.DAVFile</pytype>
      <properties>
        <acl>
          <ace>
            <principal><authenticated/></principal>
            <grant><privilege><read/></privilege></grant>
            <protected/>
          </ace>
          <ace>
            <principal><href>/principals/users/admin</href></principal>
            <grant><privilege><all/></privilege></grant>
            <protected/>
            <inheritable/>
          </ace>
        </acl>
      </properties>
      <members>
        <!--
          We must define the calendar home location before the
          principals as auto-provisioning of accounts occurs when the
          principal collections are created and we need to have the
          calendar home path setup by then.
         -->
        <collection name="calendars" tag="calendars">
          <pytype>twistedcaldav.static.CalDAVFile</pytype>
          <properties>
            <acl>
              <ace>
                <principal><authenticated/></principal>
                <grant><privilege><read/></privilege></grant>
                <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="groups">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="resources">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="public">
              <properties>
                <acl>
                  <ace>
                    <principal><unauthenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
          </members>
        </collection>
        <collection name="principals" initialize="yes">
          <pytype>twistedcaldav.directory.resource.DirectoryPrincipalProvisioningResource</pytype>
          <params>
            <param>
              <key>DirectoryNode</key>
              <value>/Search</value>
            </param>
          </params>
          <properties>
            <acl>
              <ace>
                <principal><authenticated/></principal>
                <grant><privilege><read/></privilege></grant>
                <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users" tag="principals">
              <pytype>twistedcaldav.directory.resource.DirectoryUserPrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="groups" tag="principals">
              <pytype>twistedcaldav.directory.resource.DirectoryGroupPrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="resources" tag="principals">
              <pytype>twistedcaldav.directory.resource.DirectoryResourcePrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
          </members>
        </collection>
      </members>
    </collection>
  </docroot>

  <authentication>
  	<basic enable="yes" onlyssl="yes" credentials="directory">
  	  <realm></realm>
  	</basic>
  	<digest enable="no" onlyssl="no" credentials="property">
  	  <realm></realm>
  	</digest>
  	<kerberos enable="no" onlyssl="no">
  	  <service></service>
  	</kerberos>
  </authentication>

  <accounts/>

</repository>

=== svn2github/calendarserver-raw/CalendarServer/trunk/conf/repository-proxy.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE repository SYSTEM "repository.dtd">

<repository>

  <docroot auto-principal-collection-set="no">
    <collection>
      <pytype>twisted.web2.dav.static.DAVFile</pytype>
      <properties>
        <acl>
          <ace>
            <principal><authenticated/></principal>
            <grant><privilege><read/></privilege></grant>
            <protected/>
          </ace>
          <ace>
            <principal><href>/principals/users/admin</href></principal>
            <grant><privilege><all/></privilege></grant>
            <protected/>
            <inheritable/>
          </ace>
        </acl>
        <!--
          Must explicitly set which principal hierarchies will be
          listed in WebDAV properties.  The order of these will
          determine how a user id will map to a principal in a
          particular hierarchy if an id appears in more than one.
         -->
        <prop><principal-collection-set xmlns="DAV:"><href>/principals/localusers/</href><href>/principals/users/</href><href>/principals/users/</href><href>/principals/groups/</href><href>/principals/resources/</href></principal-collection-set></prop>
      </properties>
      <members>
        <!--
          We must define the calendar home location before the
          principals as auto-provisioning of accounts occurs when the
          principal collections are created and we need to have the
          calendar home path setup by then.
         -->
        <collection name="calendars" tag="calendars">
          <pytype>twistedcaldav.static.CalDAVFile</pytype>
          <properties>
            <acl>
              <ace>
                <principal><authenticated/></principal>
                <grant><privilege><read/></privilege></grant>
                <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="groups">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="resources">
              <pytype>twistedcaldav.static.CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="public">
              <properties>
                <acl>
                  <ace>
                    <principal><unauthenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
          </members>
        </collection>
        <collection name="principals">
          <pytype>twistedcaldav.directory.DirectoryPrincipalProvisioningResource</pytype>
          <params>
            <param>
              <key>DirectoryNode</key>
              <value>/Search</value>
            </param>
          </params>
          <properties>
            <acl>
              <ace>
                <principal><authenticated/></principal>
                <grant><privilege><read/></privilege></grant>
                <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users">
              <pytype>twistedcaldav.directory.DirectoryUserPrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="groups">
              <pytype>twistedcaldav.directory.DirectoryGroupPrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="resources">
              <pytype>twistedcaldav.directory.DirectoryResourcePrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="localusers" tag="principals">
              <pytype>twistedcaldav.static.CalendarPrincipalCollectionFile</pytype>
                <properties>
                  <acl>
                    <ace>
                      <principal><href>/principals/users/admin</href></principal>
                      <grant><privilege><read/></privilege></grant>
                      <protected/>
                    </ace>
                  </acl>
                </properties>
              <members/>
            </collection>
          </members>
        </collection>
      </members>
    </collection>
  </docroot>

  <authentication>
    <basic enable="yes" onlyssl="yes" credentials="directory">
      <realm></realm>
    </basic>
    <digest enable="no" onlyssl="no" credentials="property">
      <realm></realm>
    </digest>
    <kerberos enable="no" onlyssl="no">
      <service></service>
    </kerberos>
  </authentication>

<accounts>
  <user>
    <uid>proxy</uid>
    <pswd>proxy</pswd>
    <name>User who can authorize as someone else</name>
    <canproxy/>
  </user>
</accounts>

</repository>

=== svn2github/calendarserver-raw/CalendarServer/trunk/conf/repository-static.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE repository SYSTEM "repository.dtd">

<repository>

  <docroot>
    <collection>
      <pytype>DAVFile</pytype>
      <properties>
        <acl>
          <ace>
            <principal><authenticated/></principal>
            <grant><privilege><read/></privilege></grant>
            <protected/>
          </ace>
          <ace>
            <principal><href>/principals/users/admin</href></principal>
            <grant><privilege><all/></privilege></grant>
            <protected/>
            <inheritable/>
          </ace>
        </acl>
      </properties>
      <members>
        <collection name="principals">
          <pytype>CalendarPrincipalProvisioningResource</pytype>
          <properties>
            <acl>
              <ace>
                <principal><authenticated/></principal>
                <grant><privilege><read/></privilege></grant>
                <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users" tag="principals">
              <pytype>CalendarUserPrincipalProvisioningResource</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
          </members>
        </collection>
        <collection name="calendars">
          <pytype>CalDAVFile</pytype>
          <properties>
            <acl>
              <ace>
              <principal><authenticated/></principal>
              <grant><privilege><read/></privilege></grant>
              <protected/>
              </ace>
            </acl>
          </properties>
          <members>
            <collection name="users" tag="calendars">
              <pytype>CalendarHomeProvisioningFile</pytype>
              <properties>
                <acl>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
            <collection name="shared">
              <properties>
                <acl>
                  <ace>
                    <principal><unauthenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                  <ace>
                    <principal><authenticated/></principal>
                    <grant><privilege><read/></privilege></grant>
                    <protected/>
                    <inheritable/>
                  </ace>
                </acl>
              </properties>
              <members/>
            </collection>
          </members>
        </collection>
      </members>
    </collection>
  </docroot>

  <accounts>
    <user>
      <uid>admin</uid>
      <pswd>admin</pswd>
      <name>Super User</name>
    </user>
    <!--
    <user repeat='99'>
      <uid>user%02d</uid>
      <pswd>user%02d</pswd>
      <name>User %02d</name>
      <calendar>calendar</calendar>
    </user>
    <user repeat='10'>
      <uid>public%02d</uid>
      <pswd/>
      <name>Public %02d</name>
      <calendar>calendar</calendar>
      <acl>
        <ace>
          <principal><all/></principal>
          <grant><privilege><all/></privilege></grant>
          <protected/>
          <inheritable/>
        </ace>
      </acl>
    </user>
    <user repeat='10'>
      <uid>resource%02d</uid>
      <pswd/>
      <name>Room %02d</name>
      <calendar>calendar</calendar>
      <acl>
        <ace>
          <principal><all/></principal>
          <grant><privilege><all/></privilege></grant>
          <protected/>
          <inheritable/>
        </ace>
      <autorespond/>
      </acl>
    </user>
     -->
  </accounts>

</repository>
