=== svn2github/calendarserver-raw/CalendarServer/branches/release/CalendarServer-3.1-dev/conf/auth/accounts.dtd
<!--
Copyright (c) 2006-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!ELEMENT accounts (user*, group*, resource*, location*) >
  <!ATTLIST accounts realm CDATA "">

  <!ELEMENT user (uid*, guid, password?, name?, first-name?, last-name?, email-address*)>
    <!ATTLIST user repeat CDATA "1">

  <!ELEMENT group (uid*, guid, password?, name?, members)>
    <!ATTLIST group repeat CDATA "1">

  <!ELEMENT resource (uid*, guid, password?, name?,)>
    <!ATTLIST resource repeat CDATA "1">

  <!ELEMENT location (uid*, guid, password?, name?,)>
    <!ATTLIST location repeat CDATA "1">

  <!ELEMENT member (#PCDATA)>
    <!ATTLIST member type (users|groups|locations|resources) "users">

  <!ELEMENT uid               (#PCDATA)>
  <!ELEMENT guid              (#PCDATA)>
  <!ELEMENT password          (#PCDATA)>
  <!ELEMENT name              (#PCDATA)>
  <!ELEMENT first-name        (#PCDATA)>
  <!ELEMENT last-name         (#PCDATA)>
  <!ELEMENT email-address     (#PCDATA)>
  <!ELEMENT members           (member*)>
>

=== svn2github/calendarserver-raw/CalendarServer/branches/new-store/conf/auth/accounts-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "accounts.dtd">

<accounts realm="Test Realm">
  <user>
    <uid>admin</uid>
    <guid>admin</guid>
    <password>admin</password>
    <name>Super User</name>
    <first-name>Super</first-name>
    <last-name>User</last-name>
  </user>
  <user>
    <uid>apprentice</uid>
    <guid>apprentice</guid>
    <password>apprentice</password>
    <name>Apprentice Super User</name>
    <first-name>Apprentice</first-name>
    <last-name>Super User</last-name>
  </user>
  <user>
    <uid>wsanchez</uid>
    <guid>wsanchez</guid>
    <email-address>wsanchez@apple.com</email-address>
    <password>test</password>
    <name>Wilfredo Sanchez Vega</name>
    <first-name>Wilfredo</first-name>
    <last-name>Sanchez Vega</last-name>
  </user>
  <user>
    <uid>cdaboo</uid>
    <guid>cdaboo</guid>
    <email-address>cdaboo@apple.com</email-address>
    <password>test</password>
    <name>Cyrus Daboo</name>
    <first-name>Cyrus</first-name>
    <last-name>Daboo</last-name>
  </user>
  <user>
    <uid>sagen</uid>
    <guid>sagen</guid>
    <email-address>sagen@apple.com</email-address>
    <password>test</password>
    <name>Morgen Sagen</name>
    <first-name>Morgen</first-name>
    <last-name>Sagen</last-name>
  </user>
  <user>
    <uid>dre</uid>
    <guid>andre</guid>
    <email-address>dre@apple.com</email-address>
    <password>test</password>
    <name>Andre LaBranche</name>
    <first-name>Andre</first-name>
    <last-name>LaBranche</last-name>
  </user>
  <user>
    <uid>glyph</uid>
    <guid>glyph</guid>
    <email-address>glyph@apple.com</email-address>
    <password>test</password>
    <name>Glyph Lefkowitz</name>
    <first-name>Glyph</first-name>
    <last-name>Lefkowitz</last-name>
  </user>
  <user repeat="99">
    <uid>user%02d</uid>
    <uid>User %02d</uid>
    <guid>user%02d</guid>
    <password>user%02d</password>
    <name>User %02d</name>
    <first-name>User</first-name>
    <last-name>%02d</last-name>
    <email-address>user%02d@example.com</email-address>
  </user>
  <user repeat="10">
    <uid>public%02d</uid>
    <guid>public%02d</guid>
    <password>public%02d</password>
    <name>Public %02d</name>
    <first-name>Public</first-name>
    <last-name>%02d</last-name>
  </user>
  <group>
    <uid>group01</uid>
    <guid>group01</guid>
    <password>group01</password>
    <name>Group 01</name>
    <members>
      <member type="users">user01</member>
    </members>
  </group>
  <group>
    <uid>group02</uid>
    <guid>group02</guid>
    <password>group02</password>
    <name>Group 02</name>
    <members>
      <member type="users">user06</member>
      <member type="users">user07</member>
    </members>
  </group>
  <group>
    <uid>group03</uid>
    <guid>group03</guid>
    <password>group03</password>
    <name>Group 03</name>
    <members>
      <member type="users">user08</member>
      <member type="users">user09</member>
    </members>
  </group>
  <group>
    <uid>group04</uid>
    <guid>group04</guid>
    <password>group04</password>
    <name>Group 04</name>
    <members>
      <member type="groups">group02</member>
      <member type="groups">group03</member>
      <member type="users">user10</member>
    </members>
  </group>
  <group>
    <uid>disabledgroup</uid>
    <guid>disabledgroup</guid>
    <password>disabledgroup</password>
    <name>Disabled Group</name>
    <members>
      <member type="users">user01</member>
    </members>
  </group>
  <location>
    <uid>mercury</uid>
    <guid>mercury</guid>
    <password>test</password>
    <name>Mecury Conference Room, Building 1, 2nd Floor</name>
  </location>
  <location>
    <uid>venus</uid>
    <guid>venus</guid>
    <password>test</password>
    <name>Venus Conference Room, Building 1, 2nd Floor</name>
  </location>
  <location>
    <uid>Earth</uid>
    <guid>Earth</guid>
    <password>test</password>
    <name>Earth Conference Room, Building 1, 1st Floor</name>
  </location>
  <location>
    <uid>mars</uid>
    <guid>mars</guid>
    <password>test</password>
    <name>Mars Conference Room, Building 1, 1st Floor</name>
  </location>
  <location>
    <uid>jupiter</uid>
    <guid>jupiter</guid>
    <password>test</password>
    <name>Jupiter Conference Room, Building 2, 1st Floor</name>
  </location>
  <location>
    <uid>neptune</uid>
    <guid>neptune</guid>
    <password>test</password>
    <name>Neptune Conference Room, Building 2, 1st Floor</name>
  </location>
  <location>
    <uid>pluto</uid>
    <guid>pluto</guid>
    <password>test</password>
    <name>Pluto Conference Room, Building 2, 1st Floor</name>
  </location>
  <location>
    <uid>saturn</uid>
    <guid>saturn</guid>
    <password>test</password>
    <name>Saturn Conference Room, Building 2, 1st Floor</name>
  </location>
  <location>
    <uid>uranus</uid>
    <guid>uranus</guid>
    <password>test</password>
    <name>Uranus Conference Room, Building 3, 1st Floor</name>
  </location>
</accounts>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/dreid/principalsOnDemand-114/conf/accounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "accounts.dtd">

<accounts realm="Test Realm">
  <user>
    <uid>admin</uid>
    <password>admin</password>
    <name>Super User</name>
  </user>
  <user>
    <uid>proxy</uid>
    <password>proxy</password>
    <name>User who can authorize as someone else</name>
    <canproxy/> <!-- FIXME: Is the directory the right place to configure this bit? -->
  </user>
  <user>
    <uid>test</uid>
    <password>test</password>
    <name>Test User</name>
    <cuaddr>mailto:testuser@example.com</cuaddr>
  </user>
  <group>
    <uid>users</uid>
    <password>users</password>
    <name>Users Group</name>
    <members>
      <member type="user">test</member>
    </members>
  </group>
  <resource>
    <uid>mercury</uid>
    <password>mercury</password>
    <name>Mecury Conference Room, Building 1, 2nd Floor</name>
  </resource>
</accounts>

=== svn2github/calendarserver-raw/CalendarServer/branches/release/CalendarServer-1.1-dev/twistedcaldav/directory/test/accounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2007 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/accounts.dtd">

<accounts realm="Test">
  <user>
    <uid>admin</uid>
    <guid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</guid>
    <password>nimda</password>
    <name>Administrators</name>
  </user>
  <user>
    <uid>wsanchez</uid>
    <guid>6423F94A-6B76-4A3A-815B-D52CFD77935D</guid>
    <password>zehcnasw</password>
    <name>Wilfredo Sanchez</name>
    <cuaddr>mailto:wsanchez@example.com</cuaddr>
  </user>
  <user>
    <uid>cdaboo</uid>
    <guid>5A985493-EE2C-4665-94CF-4DFEA3A89500</guid>
    <password>oobadc</password>
    <name>Cyrus Daboo</name>
    <cuaddr>mailto:cdaboo@example.com</cuaddr>
  </user>
  <user>
    <uid>lecroy</uid>
    <guid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</guid>
    <password>yorcel</password>
    <name>Chris Lecroy</name>
    <cuaddr>mailto:lecroy@example.com</cuaddr>
  </user>
  <user>
    <uid>dreid</uid>
    <guid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</guid>
    <password>dierd</password>
    <name>David Reid</name>
    <cuaddr>mailto:dreid@example.com</cuaddr>
  </user>
  <user repeat="2">
    <uid>user%02d</uid>
    <password>%02duser</password>
    <name>User %02d</name>
  </user>
  <group>
    <uid>managers</uid>
    <password>managers</password>
    <name>Managers</name>
    <members>
      <member type="users">lecroy</member>
    </members>
  </group>
  <group>
    <uid>admin</uid>
    <password>admin</password>
    <name>Administrators</name>
    <members>
      <member type="groups">managers</member>
    </members>
  </group>
  <group>
    <uid>grunts</uid>
    <password>grunts</password>
    <name>We do all the work</name>
    <members>
      <member>wsanchez</member>
      <member>cdaboo</member>
      <member>dreid</member>
    </members>
  </group>
  <group>
    <uid>right_coast</uid>
    <password>right_coast</password>
    <name>East Coast</name>
    <members>
      <member>cdaboo</member>
    </members>
  </group>
  <group>
    <uid>left_coast</uid>
    <password>left_coast</password>
    <name>West Coast</name>
    <members>
      <member>wsanchez</member>
      <member>lecroy</member>
      <member>dreid</member>
    </members>
  </group>
  <group>
    <uid>both_coasts</uid>
    <password>both_coasts</password>
    <name>Both Coasts</name>
    <members>
      <member type="groups">right_coast</member>
      <member type="groups">left_coast</member>
    </members>
  </group>
  <group>
    <uid>recursive1_coasts</uid>
    <password>recursive1_coasts</password>
    <name>Recursive1 Coasts</name>
    <members>
      <member type="groups">recursive2_coasts</member>
      <member>wsanchez</member>
    </members>
  </group>
  <group>
    <uid>recursive2_coasts</uid>
    <password>recursive2_coasts</password>
    <name>Recursive2 Coasts</name>
    <members>
      <member type="groups">recursive1_coasts</member>
      <member>cdaboo</member>
    </members>
  </group>
  <group>
    <uid>non_calendar_group</uid>
    <password>non_calendar_group</password>
    <name>Non-calendar group</name>
    <members>
      <member>cdaboo</member>
      <member>lecroy</member>
    </members>
    <disable-calendar/>
  </group>
  <location>
    <uid>mercury</uid>
    <password>mercury</password>
    <name>Mecury Seven</name>
    <cuaddr>mailto:mercury@example.com</cuaddr>
    <proxies>
      <member type="groups">left_coast</member>
    </proxies>
  </location>
  <location>
    <uid>gemini</uid>
    <password>gemini</password>
    <name>Gemini Twelve</name>
    <cuaddr>mailto:gemini@example.com</cuaddr>
    <auto-schedule/>
    <proxies>
      <member>wsanchez</member>
    </proxies>
  </location>
  <location>
    <uid>apollo</uid>
    <password>apollo</password>
    <name>Apollo Eleven</name>
    <cuaddr>mailto:apollo@example.com</cuaddr>
    <proxies>
      <member type="groups">both_coasts</member>
    </proxies>
  </location>
  <location>
    <uid>orion</uid>
    <password>orion</password>
    <name>Orion</name>
    <cuaddr>mailto:orion@example.com</cuaddr>
    <proxies>
      <member type="groups">recursive1_coasts</member>
    </proxies>
  </location>
  <resource>
    <uid>transporter</uid>
    <password>transporter</password>
    <name>Mass Transporter</name>
    <cuaddr>mailto:transporter@example.com</cuaddr>
  </resource>
  <resource>
    <uid>ftlcpu</uid>
    <password>ftlcpu</password>
    <name>Faster-Than-Light Microprocessor</name>
    <cuaddr>mailto:ftlcpu@example.com</cuaddr>
  </resource>
  <resource>
    <uid>non_calendar_proxy</uid>
    <guid>non_calendar_proxy</guid>
    <password>non_calendar_proxy</password>
    <name>Non-calendar proxy</name>
    <cuaddr>mailto:non_calendar_proxy@example.com</cuaddr>
    <proxies>
      <member type="groups">non_calendar_group</member>
    </proxies>
  </resource>
</accounts>

=== svn2github/calendarserver-raw/CalendarServer/branches/users/gaya/sharedgroups/twistedcaldav/directory/test/accounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2013 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/accounts.dtd">

<accounts realm="Test">
  <user>
    <uid>admin</uid>
    <guid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</guid>
    <password>nimda</password>
    <name>Administrators</name>
  </user>
  <user>
    <uid>wsanchez</uid>
    <guid>6423F94A-6B76-4A3A-815B-D52CFD77935D</guid>
    <password>zehcnasw</password>
    <name>Wilfredo Sanchez</name>
    <email-address>wsanchez@example.com</email-address>
  </user>
  <user>
    <uid>cdaboo</uid>
    <guid>5A985493-EE2C-4665-94CF-4DFEA3A89500</guid>
    <password>oobadc</password>
    <name>Cyrus Daboo</name>
    <email-address>cdaboo@example.com</email-address>
  </user>
  <user>
    <uid>lecroy</uid>
    <guid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</guid>
    <password>yorcel</password>
    <name>Chris Lecroy</name>
    <email-address>lecroy@example.com</email-address>
  </user>
  <user>
    <uid>dreid</uid>
    <guid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</guid>
    <password>dierd</password>
    <name>David Reid</name>
    <email-address>dreid@example.com</email-address>
  </user>
  <user>
    <uid>doublequotes</uid>
    <guid>8E04787E-336D-41ED-A70B-D233AD0DCE6F</guid>
    <password>setouqelbuod</password>
    <name>Double "quotey" Quotes</name>
    <email-address>doublequotes@example.com</email-address>
  </user>
  <user>
    <uid>nocalendar</uid>
    <guid>543D28BA-F74F-4D5F-9243-B3E3A61171E5</guid>
    <password>radnelacon</password>
    <name>No Calendar</name>
    <email-address>nocalendar@example.com</email-address>
  </user>
  <user>
    <uid>usera</uid>
    <guid>7423F94A-6B76-4A3A-815B-D52CFD77935D</guid>
    <password>a</password>
    <name>a</name>
    <email-address>a@example.com</email-address>
  </user>
  <user>
    <uid>userb</uid>
    <guid>8A985493-EE2C-4665-94CF-4DFEA3A89500</guid>
    <password>b</password>
    <name>b</name>
    <email-address>b@example.com</email-address>
  </user>
  <user>
    <uid>userc</uid>
    <guid>9FF60DAD-0BDE-4508-8C77-15F0CA5C8DD2</guid>
    <password>c</password>
    <name>c</name>
    <email-address>c@example.com</email-address>
  </user>
  <user>
    <uid>usercalonly</uid>
    <guid>9E1FFAC4-3CCD-45A1-8272-D161C92D2EEE</guid>
    <password>a</password>
    <name>a calonly</name>
    <email-address>a-calonly@example.com</email-address>
  </user>
  <user>
    <uid>useradbkonly</uid>
    <guid>7678EC8A-A069-4E82-9066-7279C6718507</guid>
    <password>a</password>
    <name>a adbkonly</name>
    <email-address>a-adbkonly@example.com</email-address>
  </user>
  <user>
    <uid>nonascii</uid>
    <uid>nonascii佐藤</uid>
    <guid>320B73A1-46E2-4180-9563-782DFDBE1F63</guid>
    <password>a</password>
    <name>佐藤佐藤佐藤</name>
    <email-address>nonascii@example.com</email-address>
  </user>
  <user>
    <uid>delegator</uid>
    <guid>FC465590-E9E9-4746-ACE8-6C756A49FE4D</guid>
    <password>a</password>
    <name>Calendar Delegator</name>
    <email-address>calendardelegator@example.com</email-address>
  </user>
  <user>
    <uid>occasionaldelegate</uid>
    <guid>EC465590-E9E9-4746-ACE8-6C756A49FE4D</guid>
    <password>a</password>
    <name>Occasional Delegate</name>
    <email-address>occasional@example.com</email-address>
  </user>
    <user>
    <uid>delegateviagroup</uid>
    <guid>46D9D716-CBEE-490F-907A-66FA6C3767FF</guid>
    <password>a</password>
    <name>Delegate Via Group</name>
    <email-address>delegateviagroup@example.com</email-address>
  </user>
  <group>
    <uid>delegategroup</uid>
    <guid>00599DAF-3E75-42DD-9DB7-52617E79943F</guid>
    <name>Delegate Group</name>
    <members>
      <member type="users">delegateviagroup</member>
    </members>
  </group>
  <user repeat="2">
    <uid>user%02d</uid>
    <guid>user%02d</guid>
    <password>%02duser</password>
    <name>~35 User %02d</name>
    <first-name>~5</first-name>
    <last-name>~9 User %02d</last-name>
    <email-address>~10@example.com</email-address>
  </user>
  <group>
    <uid>managers</uid>
    <guid>9FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</guid>
    <password>managers</password>
    <name>Managers</name>
    <members>
      <member type="users">lecroy</member>
    </members>
  </group>
  <group>
    <uid>admin</uid>
    <guid>admin</guid>
    <password>admin</password>
    <name>Administrators</name>
    <members>
      <member type="groups">managers</member>
    </members>
  </group>
  <group>
    <uid>grunts</uid>
    <guid>grunts</guid>
    <password>grunts</password>
    <name>We do all the work</name>
    <members>
      <member>wsanchez</member>
      <member>cdaboo</member>
      <member>dreid</member>
    </members>
  </group>
  <group>
    <uid>right_coast</uid>
    <guid>right_coast</guid>
    <password>right_coast</password>
    <name>East Coast</name>
    <members>
      <member>cdaboo</member>
    </members>
  </group>
  <group>
    <uid>left_coast</uid>
    <guid>left_coast</guid>
    <password>left_coast</password>
    <name>West Coast</name>
    <members>
      <member>wsanchez</member>
      <member>lecroy</member>
      <member>dreid</member>
    </members>
  </group>
  <group>
    <uid>both_coasts</uid>
    <guid>both_coasts</guid>
    <password>both_coasts</password>
    <name>Both Coasts</name>
    <members>
      <member type="groups">right_coast</member>
      <member type="groups">left_coast</member>
    </members>
  </group>
  <group>
    <uid>recursive1_coasts</uid>
    <guid>recursive1_coasts</guid>
    <password>recursive1_coasts</password>
    <name>Recursive1 Coasts</name>
    <members>
      <member type="groups">recursive2_coasts</member>
      <member>wsanchez</member>
    </members>
  </group>
  <group>
    <uid>recursive2_coasts</uid>
    <guid>recursive2_coasts</guid>
    <password>recursive2_coasts</password>
    <name>Recursive2 Coasts</name>
    <members>
      <member type="groups">recursive1_coasts</member>
      <member>cdaboo</member>
    </members>
  </group>
  <group>
    <uid>non_calendar_group</uid>
    <guid>non_calendar_group</guid>
    <password>non_calendar_group</password>
    <name>Non-calendar group</name>
    <members>
      <member>cdaboo</member>
      <member>lecroy</member>
    </members>
  </group>
  <location>
    <uid>mercury</uid>
    <guid>mercury</guid>
    <password>mercury</password>
    <name>Mercury Seven</name>
    <email-address>mercury@example.com</email-address>
  </location>
  <location>
    <uid>gemini</uid>
    <guid>gemini</guid>
    <password>gemini</password>
    <name>Gemini Twelve</name>
    <email-address>gemini@example.com</email-address>
  </location>
  <location>
    <uid>apollo</uid>
    <guid>apollo</guid>
    <password>apollo</password>
    <name>Apollo Eleven</name>
    <email-address>apollo@example.com</email-address>
  </location>
  <location>
    <uid>orion</uid>
    <guid>orion</guid>
    <password>orion</password>
    <name>Orion</name>
    <email-address>orion@example.com</email-address>
  </location>
  <resource>
    <uid>transporter</uid>
    <guid>transporter</guid>
    <password>transporter</password>
    <name>Mass Transporter</name>
    <email-address>transporter@example.com</email-address>
  </resource>
  <resource>
    <uid>ftlcpu</uid>
    <guid>ftlcpu</guid>
    <password>ftlcpu</password>
    <name>Faster-Than-Light Microprocessor</name>
    <email-address>ftlcpu@example.com</email-address>
  </resource>
  <resource>
    <uid>non_calendar_proxy</uid>
    <guid>non_calendar_proxy</guid>
    <password>non_calendar_proxy</password>
    <name>Non-calendar proxy</name>
    <email-address>non_calendar_proxy@example.com</email-address>
  </resource>
  <resource>
    <uid>disabled</uid>
    <guid>disabled</guid>
    <password>disabled</password>
    <name>Disabled Record</name>
    <email-address>disabled@example.com</email-address>
  </resource>
</accounts>

=== svn2github/calendarserver-raw/CalendarServer/branches/release/CalendarServer-5.2-dev/calendarserver/tools/test/calverify/accounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2013 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/accounts.dtd">

<accounts realm="/Search">
  <user>
    <uid>example1</uid>
    <guid>D46F3D71-04B7-43C2-A7B6-6F92F92E61D0</guid>
    <password>example</password>
    <name>Example User1</name>
    <email-address>example1@example.com</email-address>
  </user>
  <user>
    <uid>example2</uid>
    <guid>47B16BB4-DB5F-4BF6-85FE-A7DA54230F92</guid>
    <password>example</password>
    <name>Example User2</name>
    <email-address>example2@example.com</email-address>
  </user>
  <user>
    <uid>example3</uid>
    <guid>AC478592-7783-44D1-B2AE-52359B4E8415</guid>
    <password>example</password>
    <name>Example User3</name>
    <email-address>example3@example.com</email-address>
  </user>
  <user>
    <uid>example4</uid>
    <guid>A89E3A97-1658-4E45-A185-479F3E49D446</guid>
    <password>example</password>
    <name>Example User4</name>
    <email-address>example4@example.com</email-address>
  </user>
</accounts>
