=== svn2github/calendarserver-raw/CalDAVTester/tags/release/CalDAVTester-1.3/scripts/monitoring/monitorinfo.dtd
<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<!ELEMENT monitorinfo (logging, period, timeout, serverinfo, start, testinfo, end, warningtime, notify?) >
	<!ATTLIST monitorinfo	name CDATA	"">

	<!ELEMENT logging		EMPTY>
		<!ATTLIST logging	enable (yes|no) "no">

	<!ELEMENT period    	(#PCDATA)>

	<!ELEMENT timeout    	(#PCDATA)>

	<!ELEMENT serverinfo	(#PCDATA)>

	<!ELEMENT start	        (#PCDATA)>

	<!ELEMENT testinfo	    (#PCDATA)>

	<!ELEMENT end    	    (#PCDATA)>

	<!ELEMENT warningtime  	(#PCDATA)>
	
	<!ELEMENT notify        (mailfrom, mailto+, subject, body)>
		<!ATTLIST notify	time-exceeded  (yes|no) "no"
							request-failed (yes|no) "yes"
							interval       CDATA    "15">
	
		<!ELEMENT mailfrom  (#PCDATA)>
		<!ELEMENT mailto    (#PCDATA)>
		<!ELEMENT subject   (#PCDATA)>
		<!ELEMENT body      (#PCDATA)>

=== svn2github/calendarserver-raw/CalDAVTester/branches/users/cdaboo/attendee-comments-2887/scripts/monitoring/monitorinfo.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE monitorinfo SYSTEM "monitorinfo.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<monitorinfo name="test.example.com">
	<logging enable="no"/>
	<period>1</period>
	<timeout>60</timeout>
	<serverinfo>scripts/server/serverinfo-monitor.xml</serverinfo>
	<start>monitor/get/get-start.xml</start>
	<testinfo>monitor/get/get-small.xml</testinfo>
	<end>monitor/get/get-end.xml</end>
	<warningtime>1.0</warningtime>
	<notify time-exceeded="no" request-failed="yes">
		<mailfrom>test@example.com</mailfrom>
		<mailto>test@example.com</mailto>
		<subject>Calendar Server error</subject>
		<body><![CDATA[Hi,
The caldav.example.com Calendar Server generated the following error:

%s

Please take the appropriate action.

Thank you.
]]></body>
	</notify>
</monitorinfo>
