=== svn2github/calendarserver-raw/CalDAVTester/trunk/caldavtest.dtd
<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<!ELEMENT caldavtest (description?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, header*, ruri?, data?, verify*, grablocation?)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grablocation EMPTY>
	
	<!ELEMENT test-suite (test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/buildperformance/client-sim/poll-ten-new.xml
<?xml version="1.0"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest ignore-all='yes'>
	<description>Performance check GET</description>

	<start/>
	
	<test-suite name='Client polling - nothing new found' ignore='no'>
		<test name='1' count='1' stats='yes'>
			<description>PROPFIND on calendar home</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<ruri>$pathprefix:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<ruri>$pathprefix:/calendar.10/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/2.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$pathprefix:/calendar.10/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/4.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/2.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/3.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/4.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/5.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/5.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/6.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/6.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/7.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/7.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/8.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/8.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/9.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/9.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request print-response="no">
				<method>PUT</method>
				<ruri>$pathprefix:/calendar/10.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/10.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/branches/users/sagen/calendarquery-3483/scripts/tests/expandproperty.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test expand-property REPORT</description>

	<start/>
	
	<test-suite name='Basic REPORT' ignore='no'>
		<test name='1'>
			<description>OK property query</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value>-</value>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$principal1:</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Missing property query</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>DAV:missing</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Two OK properties (one empty) query</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/3.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>okhrefs</name>
						<value></value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Access Control' ignore='no'>
		<test name='1'>
			<description>Set property to point to someone else's calendar</description>
			<request print-response="no">
				<method>PROPPATCH</method>
				<ruri>$pathprefix1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/4.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Try query against accessible href</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$pathprefix1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/5.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value>-</value>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix1:/</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>displayname</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Try query against inaccessible href</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$pathprefix1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/6.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value>-</value>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$pathprefix1:/</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>notcontains</name>
						<value>displayname</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Reset property</description>
			<request print-response="no">
				<method>PROPPATCH</method>
				<ruri>$pathprefix1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/7.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Invalid REPORTs' ignore='no'>
		<test name='1'>
			<description>Wrong Depth 1</description>
			<request print-response="no">
				<method>REPORT</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>400</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Wrong Depth infinity</description>
			<request print-response="no">
				<method>REPORT</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>400</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Multi-expand not supported</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$principal1:</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/8.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>501</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Membership REPORT' ignore='no'>
		<test name='1'>
			<description>Non-expanding group-member-set query</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$uids:toplevelgroup/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/9.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value>-</value>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$uids:toplevelgroup/</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 14</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>Sub Group 1</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>Sub Group 2</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>notcontains</name>
						<value>User 10</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Expanding group-member-set query</description>
			<request print-response="no">
				<method>REPORT</method>
				<ruri>$uids:toplevelgroup/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/expandproperty/10.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>prefix</name>
						<value>-</value>
					</arg>
					<arg>
						<name>okhrefs</name>
						<value>$uids:toplevelgroup/</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 10</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 11</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 12</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 13</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 14</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>Sub Group 1</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>Sub Group 2</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>User 10</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>

</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/performance/get/get-start.xml
<?xml version="1.0"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest ignore-all='yes'>
	<description>Performance check GET</description>

	<start>
		<request end-delete='no'>
			<method>PUT</method>
			<ruri>1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/performance/put/1.ics</filepath>
			</data>
		</request>
		<request end-delete='no'>
			<method>PUT</method>
			<ruri>2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/performance/put/2.ics</filepath>
			</data>
		</request>
		<request end-delete='no'>
			<method>PUT</method>
			<ruri>3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/performance/put/3.ics</filepath>
			</data>
		</request>
	</start>
	
	<test-suite/>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/scheduleacl.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start>
		<request end-delete="yes">
			<method>MKCOL</method>
			<ruri>$pathprefix:/top-collection/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<!--  Calendar with DAV:read only -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar1/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal1.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal2.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal3.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<!--  Calendar with no privileges -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar2/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal4.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal5.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal6.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<!--  Calendar with CALDAV:read-free-busy only -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar3/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal7.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal8.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal9.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<!--  Set calendar-free-busy-set to the calendars only -->
		<request>
			<method>PROPPATCH</method>
			<ruri>$pathprefix:/inbox/</ruri>
			<data substitutions='yes'>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/scheduleacl/1.xml</filepath>
			</data>
		</request>
	</start>
	
	<test-suite name='Schedule free-busy' ignore='no'>
		<test name='1'>
			<description>SCHEDULE free busy</description>
			<request user='user02' pswd='user02' print-response='yes'>
				<method>SCHEDULE</method>
				<header>
					<name>Originator</name>
					<value>mailto:user02@example.com</value>
				</header>
				<header>
					<name>Recipient</name>
					<value>mailto:user01@example.com</value>
				</header>
				<ruri>/calendars/users/user02/outbox/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/scheduleacl/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<end>
		<!--  Set calendar-free-busy-set back to default -->
		<request>
			<method>PROPPATCH</method>
			<ruri>$pathprefix:/inbox/</ruri>
			<data substitutions='yes'>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/scheduleacl/2.xml</filepath>
			</data>
		</request>
	</end>
	
</caldavtest>
