=== svn2github/calendarserver-raw/CalDAVTester/trunk/caldavtest.dtd
<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<!ELEMENT caldavtest (description?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, header*, ruri?, data?, verify*, grablocation?)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grablocation EMPTY>
	
	<!ELEMENT test-suite (test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/recurrenceput.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<description>Test PUT method in CalDAV with various recurrences to ensure
	proper behaviour of server indexing</description>

	<start/>
	
	<test-suite name='VEVENTs'>
		<test name='1' ignore='no'>
			<description>PUT non-recurring timed event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>PUT non-recurring all day event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/2.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>PUT recurring (no exceptions) timed event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>3.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/3.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>PUT recurring (no exceptions) all day event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>4.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/4.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='5' ignore='no'>
			<description>PUT recurring (with exceptions) timed event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>5.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/5.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='6' ignore='no'>
			<description>PUT recurring (with exceptions) all day event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>6.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/6.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7' ignore='no'>
			<description>PUT recurring (with future exceptions) timed event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>7.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/7.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='8' ignore='no'>
			<description>PUT recurring (with future exceptions) all day event</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>8.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/recurrenceput/8.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='VTODOs' ignore='no'>
		<test name='1' ignore='no'>
			<description>Plain VTODO with no date - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>1todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/5.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>Plain VTODO with all-day DUE only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>2todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/6.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>Plain VTODO with all-day DTSTART/DURATION only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>3todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/7.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>Plain VTODO with all-day DTSTART only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>3todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/8.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='5' ignore='no'>
			<description>Plain VTODO with timed DUE only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>4todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/9.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='6' ignore='no'>
			<description>Plain VTODO with timed DTSTART/DURATION only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>5todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/10.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7' ignore='no'>
			<description>Plain VTODO with timed DTSTART/DURATION only - recurring</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>5todo.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/todo/11.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/branches/users/cdaboo/pycard/performance/schedule-invite/schedule-tests.xml
<?xml version="1.0"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<start>
		<request>
			<method>DELETEALL</method>
			<ruri>$pathprefix1:/outbox/</ruri>
		</request>
		<request>
			<method>DELETEALL</method>
			<ruri>$pathprefix1:/inbox/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$pathprefix2:/outbox/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$pathprefix2:/inbox/</ruri>
		</request>
		<request user="$userid3:" pswd="$pswd3:">
			<method>DELETEALL</method>
			<ruri>$pathprefix3:/outbox/</ruri>
		</request>
		<request user="$userid3:" pswd="$pswd3:">
			<method>DELETEALL</method>
			<ruri>$pathprefix3:/inbox/</ruri>
		</request>
	</start>
	
	
	<test-suite name='POST (invite)' ignore='no'>
		<test name='1' count='10' stats='yes' ignore='no'>
			<description>POST to Outbox of regular invite - small</description>
			<request>
				<method>POST</method>
				<header>
				<ruri>$pathprefix1:/outbox/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/schedule/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$^$pathprefix1:/outbox/[^/]+\.ics$</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' count='10' stats='yes' ignore='no'>
			<description>POST to Outbox of regular invite - medium</description>
			<request>
				<method>POST</method>
				<ruri>$pathprefix1:/outbox/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/schedule/2.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$^$pathprefix1:/outbox/[^/]+\.ics$</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3' count='10' stats='yes' ignore='no'>
			<description>POST to Outbox of regular invite - large</description>
			<request>
				<method>POST</method>
				<ruri>$pathprefix1:/outbox/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/performance/schedule/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$^$pathprefix1:/outbox/[^/]+\.ics$</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/tags/release/CalDAVTester-1.3/scripts/tests/timezones.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<description>Test timezone cache</description>

	<start/>
	
	<test-suite name='Timezone cache'>
		<test name='1'>
			<description>PUT event with truncated timezone in April</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/timezones/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>query for free busy with time range</description>
			<request print-response='no'>
				<method>REPORT</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/timezones/2.xml</filepath>
				</data>
				<verify>
					<callback>freeBusy</callback>
					<arg>
						<name>busy</name>
						<value>20070401T143000Z/20070401T153000Z</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PUT event with truncated timezone in December</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>3.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/timezones/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>query for free busy with time range</description>
			<request print-response='no'>
				<method>REPORT</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/timezones/2.xml</filepath>
				</data>
				<verify>
					<callback>freeBusy</callback>
					<arg>
						<name>busy</name>
						<value>20070401T143000Z/20070401T153000Z</value>
						<value>20071210T153000Z/20071210T163000Z</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Timezone cache - aliases'>
		<test name='1'>
			<description>PUT event with truncated timezone in April</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>4.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/timezones/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>query for free busy with time range</description>
			<request print-response='no'>
				<method>REPORT</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/timezones/2.xml</filepath>
				</data>
				<verify>
					<callback>freeBusy</callback>
					<arg>
						<name>busy</name>
						<value>20070401T143000Z/20070401T153000Z</value>
						<value>20071210T153000Z/20071210T163000Z</value>
						<value>20070402T150000Z/20070402T160000Z</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PUT event with truncated timezone in December</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>5.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/timezones/5.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>query for free busy with time range</description>
			<request print-response='no'>
				<method>REPORT</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/timezones/2.xml</filepath>
				</data>
				<verify>
					<callback>freeBusy</callback>
					<arg>
						<name>busy</name>
						<value>20070401T143000Z/20070401T153000Z</value>
						<value>20071210T153000Z/20071210T163000Z</value>
						<value>20070402T150000Z/20070402T160000Z</value>
						<value>20071211T140000Z/20071211T150000Z</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/branches/users/cdaboo/implicit-2661/scripts/tests/implicitdefaultcalendar.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<description>Test default calendar behavior in CalDAV</description>

	<start/>
	
	<test-suite name='Default Property' ignore='no'>
		<test name='1'>
			<description>Look for empty property on inbox</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL$&lt;href xmlns="DAV:"&gt;$calendarpath1:&lt;/href&gt;</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Set empty Property' ignore='no'>
		<test name='1'>
			<description>Set property on Inbox</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/4.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Verify property on inbox</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL$</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Set valid Property' ignore='no'>
		<test name='1'>
			<description>Look for empty property on inbox</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL$</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Set property on Inbox</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Verify property on inbox</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL$&lt;href xmlns="DAV:"&gt;$calendarpath1:&lt;/href&gt;</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Set invalid Property' ignore='no'>
		<test name='1'>
			<description>Set property on Inbox</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/3.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Verify property on inbox</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<ruri>$pathprefix:/$inbox:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/implicit/defaultcalendar/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>urn:ietf:params:xml:ns:caldavschedule-default-calendar-URL$&lt;href xmlns="DAV:"&gt;$calendarpath1:&lt;/href&gt;</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/branches/users/cdaboo/deployment/scripts/tests/schedulelargeheader.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest ignore-all='yes'>
	<description>Test POST method in CalDAV</description>

	<start/>
	
	<test-suite name="POSTs" ignore='no'>
		<test name='1'>
			<description>POST which should work</description>
			<request print-response='no'>
				<method>POST</method>
				<header>
					<name>Originator</name>
					<value>$cuaddr1:</value>
				</header>
				<header>
					<name>Recipient</name>
					<value>$cuaddr1:, $cuaddr2:, $cuaddr3:, $cuaddr4:, $cuaddr5:, $cuaddr6:, $cuaddr7:, $cuaddr8:, $cuaddr9:, $cuaddr10:, $cuaddr11:, $cuaddr12:, $cuaddr13:, $cuaddr14:, $cuaddr15:, $cuaddr16:, $cuaddr17:, $cuaddr18:, $cuaddr19:, $cuaddr20:, $cuaddr21:, $cuaddr22:, $cuaddr23:, $cuaddr24:, $cuaddr25:, $cuaddr26:, $cuaddr27:, $cuaddr28:, $cuaddr29:, $cuaddr30:, $cuaddr31:, $cuaddr32:, $cuaddr33:, $cuaddr34:, $cuaddr35:, $cuaddr36:, $cuaddr37:, $cuaddr38:, $cuaddr39:, $cuaddr40:, $cuaddr41:, $cuaddr42:, $cuaddr43:, $cuaddr44:, $cuaddr45:, $cuaddr46:, $cuaddr47:, $cuaddr48:, $cuaddr49:, $cuaddr50:, $cuaddr51:, $cuaddr52:, $cuaddr53:, $cuaddr54:, $cuaddr55:, $cuaddr56:, $cuaddr57:, $cuaddr58:, $cuaddr59:, $cuaddr60:, $cuaddr61:, $cuaddr62:, $cuaddr63:, $cuaddr64:, $cuaddr65:, $cuaddr66:, $cuaddr67:, $cuaddr68:, $cuaddr69:, $cuaddr70:, $cuaddr71:, $cuaddr72:, $cuaddr73:, $cuaddr74:, $cuaddr75:, $cuaddr76:, $cuaddr77:, $cuaddr78:, $cuaddr79:, $cuaddr80:, $cuaddr81:, $cuaddr82:, $cuaddr83:, $cuaddr84:, $cuaddr85:, $cuaddr86:, $cuaddr87:, $cuaddr88:, $cuaddr89:, $cuaddr90:, $cuaddr91:, $cuaddr92:, $cuaddr93:, $cuaddr94:, $cuaddr95:, $cuaddr96:, $cuaddr97:, $cuaddr98:, $cuaddr99:</value>
				</header>
				<ruri>$pathprefix:/$outbox:/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/schedule/3.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name="POSTs free busy" ignore='no'>
		<test name='1'>
			<description>POST free busy</description>
			<request print-response='no'>
				<method>POST</method>
				<header>
					<name>Originator</name>
					<value>$cuaddr1:</value>
				</header>
				<header>
					<name>Recipient</name>
					<value>$cuaddr1:, $cuaddr2:, $cuaddr3:, $cuaddr4:, $cuaddr5:, $cuaddr6:, $cuaddr7:, $cuaddr8:, $cuaddr9:, $cuaddr10:, $cuaddr11:, $cuaddr12:, $cuaddr13:, $cuaddr14:, $cuaddr15:, $cuaddr16:, $cuaddr17:, $cuaddr18:, $cuaddr19:, $cuaddr20:, $cuaddr21:, $cuaddr22:, $cuaddr23:, $cuaddr24:, $cuaddr25:, $cuaddr26:, $cuaddr27:, $cuaddr28:, $cuaddr29:, $cuaddr30:, $cuaddr31:, $cuaddr32:, $cuaddr33:, $cuaddr34:, $cuaddr35:, $cuaddr36:, $cuaddr37:, $cuaddr38:, $cuaddr39:, $cuaddr40:, $cuaddr41:, $cuaddr42:, $cuaddr43:, $cuaddr44:, $cuaddr45:, $cuaddr46:, $cuaddr47:, $cuaddr48:, $cuaddr49:, $cuaddr50:, $cuaddr51:, $cuaddr52:, $cuaddr53:, $cuaddr54:, $cuaddr55:, $cuaddr56:, $cuaddr57:, $cuaddr58:, $cuaddr59:, $cuaddr60:, $cuaddr61:, $cuaddr62:, $cuaddr63:, $cuaddr64:, $cuaddr65:, $cuaddr66:, $cuaddr67:, $cuaddr68:, $cuaddr69:, $cuaddr70:, $cuaddr71:, $cuaddr72:, $cuaddr73:, $cuaddr74:, $cuaddr75:, $cuaddr76:, $cuaddr77:, $cuaddr78:, $cuaddr79:, $cuaddr80:, $cuaddr81:, $cuaddr82:, $cuaddr83:, $cuaddr84:, $cuaddr85:, $cuaddr86:, $cuaddr87:, $cuaddr88:, $cuaddr89:, $cuaddr90:, $cuaddr91:, $cuaddr92:, $cuaddr93:, $cuaddr94:, $cuaddr95:, $cuaddr96:, $cuaddr97:, $cuaddr98:, $cuaddr99:</value>
				</header>
				<ruri>$pathprefix:/$outbox:/</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/schedule/6.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>
