=== svn2github/calendarserver-raw/CalDAVTester/trunk/caldavtest.dtd
<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<!ELEMENT caldavtest (description?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT request (method, header*, ruri?, data?, verify*, grablocation?)>
		<!ATTLIST request auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value+)>
		
		<!ELEMENT grablocation EMPTY>
	
	<!ELEMENT test-suite (test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no">
	
		<!ELEMENT test (description?, request+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no">

=== svn2github/calendarserver-raw/CalDAVTester/trunk/proppatch.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start/>
	
	<test-suite name='prop patches'>
		<test name='1'>
			<description>PROPPATCH of details: good</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>DAV:details</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>DAV:details$My Name</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPPATCH of details: remove it</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/3.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>DAV:details</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>DAV:details</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPPATCH remove non-existant</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/4.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>DAV:missing</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPPATCH of resourcetype: fails</description>
			<request print-response='no'>
				<method>PROPPATCH</method>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/proppatches/5.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>DAV:details</value>
						<value>DAV:resourcetype</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/mkcalendar.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start/>
	
	<test-suite name='MKCALENDAR without body'>
		<test name='1'>
			<description>Simple MKCALENDAR</description>
			<request end-delete='yes'>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest1/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>201</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>MKCALENDAR on existing resource</description>
			<request>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest1/</ruri>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>DAV:resource-must-be-null</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>MKCALENDAR inside another calendar</description>
			<request>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest1/caltest2/</ruri>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>urn:ietf:params:xml:ns:caldavcalendar-collection-location-ok</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>MKCOL inside a calendar</description>
			<request>
				<method>MKCOL</method>
				<ruri>$pathprefix:/caltest1/collection/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='MKCALENDAR with body'>
		<test name='1'>
			<description>MKCALENDAR with correct request body</description>
			<request end-delete='yes'>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest2/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/mkcalendar/1.txt</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>201</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>MKCALENDAR with correct request body on existing resource</description>
			<request>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest2/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/mkcalendar/1.txt</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>DAV:resource-must-be-null</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>MKCALENDAR with incorrect request body</description>
			<request end-delete='yes' print-response='no'>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest3/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/mkcalendar/2.txt</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>DAV:getetag</value>
						<value>DAV:displayname</value>
						<value>urn:ietf:params:xml:ns:caldavcalendar-description</value>
					</arg>
				</verify>
			</request>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$pathprefix:/caltest3/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>MKCALENDAR with incorrect request body on existing resource</description>
			<request>
				<method>MKCALENDAR</method>
				<ruri>$pathprefix:/caltest2/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/mkcalendar/2.txt</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>DAV:resource-must-be-null</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>

</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/attachments.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<description>Test attachments with CalDAV</description>

	<start/>
	
	<test-suite name='Inline'>
		<test name='1' ignore='no'>
			<description>VEVENT with image/jpeg</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/attachments/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>1.ics</ruri>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>ATTACH;FMTTYPE=image/jpeg;ENCODING=BASE64;VALUE=BINARY:</value>
					</arg>
					<arg>
						<name>contains</name>
						<value>RQAUUUUAFFFFAH//2Q==</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>VTODO with image/jpeg</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/attachments/2.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>2.ics</ruri>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>ATTACH;FMTTYPE=image/jpeg;ENCODING=BASE64;VALUE=BINARY:</value>
					</arg>
					<arg>
						<name>contains</name>
						<value>RQAUUUUAFFFFAH//2Q==</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='External'>
		<test name='1' ignore='no'>
			<description>VEVENT with http://</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>3.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/attachments/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>3.ics</ruri>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>ATTACHMENT:http://www.example.com/test.jpg</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>VTODO with image/jpeg</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>4.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/attachments/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>4.ics</ruri>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>ATTACHMENT:http://www.example.com/test.jpg</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/buildperformance/client-sim/poll-nothing-new.xml
<?xml version="1.0"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2007 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest ignore-all='yes'>
	<description>Performance check GET</description>

	<start/>
	
	<test-suite name='Client polling - nothing new found' ignore='no'>
		<test name='1' count='1' stats='yes'>
			<description>PROPFIND on calendar home</description>
			<request>
				<method>PROPFIND</method>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<ruri>$pathprefix:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/performance/client-sim/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== svn2github/calendarserver-raw/CalDAVTester/trunk/depthreportsacl.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006 Apple Computer, Inc. All rights reserved.

 This file contains Original Code and/or Modifications of Original Code
 as defined in and that are subject to the Apple Public Source License
 Version 2.0 (the 'License'). You may not use this file except in
 compliance with the License. Please obtain a copy of the License at
 http://www.opensource.apple.com/apsl/ and read it before using this
 file.

 The Original Code and all software distributed under the License are
 distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 Please see the License for the specific language governing rights and
 limitations under the License.

 DRI: Cyrus Daboo, cdaboo@apple.com
 -->

<caldavtest>
	<start>
		<request end-delete="yes">
			<method>MKCOL</method>
			<ruri>$pathprefix:/top-collection/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<!--  Calendar with DAV:read only -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar1/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal1.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal2.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar1/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal3.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar1/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<!--  Calendar with no privileges -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar2/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal4.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal5.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar2/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal6.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar2/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<!--  Calendar with CALDAV:read-free-busy only -->
		<request>
			<method>MKCALENDAR</method>
			<ruri>$pathprefix:/top-collection/calendar3/</ruri>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal7.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/1.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/1.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal8.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/2.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/2.xml</filepath>
			</data>
		</request>
		<request>
			<method>PUT</method>
			<ruri>$pathprefix:/top-collection/calendar3/3.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/cal9.ics</filepath>
			</data>
		</request>
		<request>
			<method>ACL</method>
			<ruri>$pathprefix:/top-collection/calendar3/3.ics</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/depthreportsacl/3.xml</filepath>
			</data>
		</request>
	</start>
	
	<test-suite name='Reports' ignore='no'>
		<test name='1' ignore='no'>
			<description>multiget on top collection</description>
			<request user='user02' pswd='user02' print-response='no'>
				<method>REPORT</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<ruri>$pathprefix:/top-collection/</ruri>
				<data substitutions='yes'>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/depthreportsacl/4.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>okhrefs</name>
						<value>calendar1/1.ics</value>
					</arg>
					<arg>
						<name>badhrefs</name>
						<value>calendar1/2.ics</value>
						<value>calendar1/3.ics</value>
						<value>calendar2/1.ics</value>
						<value>calendar2/2.ics</value>
						<value>calendar2/3.ics</value>
						<value>calendar3/1.ics</value>
						<value>calendar3/2.ics</value>
						<value>calendar3/3.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>query on top collection</description>
			<request user='user02' pswd='user02' print-response='no'>
				<method>REPORT</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<ruri>$pathprefix:/top-collection/</ruri>
				<data substitutions='yes'>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/depthreportsacl/5.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>okhrefs</name>
						<value>calendar1/1.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>query for free busy on collection with Depth infinity</description>
			<request user='user02' pswd='user02' print-response='no'>
				<method>REPORT</method>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<ruri>$pathprefix:/top-collection/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/depthreportsacl/6.xml</filepath>
				</data>
				<verify>
					<callback>freeBusy</callback>
					<arg>
						<name>busy</name>
						<value>20060101T060000Z/20060101T070000Z</value>
						<value>20060101T100000Z/20060101T110000Z</value>
						<value>20060101T180000Z/20060101T190000Z</value>
						<value>20060101T220000Z/20060101T230000Z</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>
